spring:
  application:
    name: security

  datasource:
    url: jdbc:mysql://localhost:3306/security_test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false